ux_icons:
    default_icon_attributes:
        width: 1.2em
        height: 1.2em
        style: 'position: relative; top: -2px;'
        xmlns: 'http://www.w3.org/2000/svg'

    aliases:
        'tabler:save-changes': 'tabler:device-floppy'
